In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib
import os
import warnings

warnings.filterwarnings("ignore")

1. 단순 회귀
2. 다중 회귀
3. 다항 회귀
4. 스플라인 회귀
5. 로지스틱 회귀
6. 규제 선형 회귀(릿지, 라쏘, 엘라스틱넷)
7. 로버스트 회귀
8. 분위수 회귀
9. 베이지안 회귀
10. 포아송 회귀
11. 음이항 회귀
12. 감마회귀

<변수선택법 까지>

## <선형 회귀>

## 1. 단순 선형회귀

In [1]:
print("""
단순 선형회귀는 독립변수가 1개인 회귀이다.
""")

단순 선형회귀는 독립변수가 1개인 회귀이다.

## 문제 1

다음과 같은 OLS 모델을 만들고 결과를 확인합니다.
- mpg 데이터를 사용하여, 상수항을 포함한 OLS 모델을 생성합니다.
- train, test 데이터는 300, 92개를 각각 사용합니다.
- 독립변수는 ["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year"]를 사용합니다.
- 종속변수는 "mpg"를 사용합니다.

In [4]:
url = "https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/mpg.csv"

df = pd.read_csv(url)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
1,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
2,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
3,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
4,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
...,...,...,...,...,...,...,...,...,...
387,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
388,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
389,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
390,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
391,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited

In [ ]:
## <수동방식>

In [8]:
from statsmodels.api import OLS, add_constant

X = df[["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year"]]
y = df["mpg"]

In [13]:
### 스케일링 
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss_array = ss.fit_transform(X)
X_scaled = pd.DataFrame(ss_array,
                        columns=X.columns)
X_scaled = add_constant(X_scaled)

In [15]:
### 데이터 분할
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(X_scaled, y,
                                                                     test_size=0.2,
                                                                     random_state=42)
print(train_input.shape, test_input.shape, train_target.shape, test_target.shape)

(313, 7) (79, 7) (313,) (79,)

In [16]:
### 다중선형회귀 모델 적합
model = OLS(train_target, train_input).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.801
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                     205.0
Date:                Thu, 21 Aug 2025   Prob (F-statistic):          4.78e-104
Time:                        12:59:50   Log-Likelihood:                -832.52
No. Observations:                 313   AIC:                             1679.
Df Residuals:                     306   BIC:                             1705.
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           23.3846      0.198    117.927      0.000      22.994      23.775
cylinders       -0.8012      0.653     -1.226      0.221      -2.087       0.485
displacement     0.6395      0.976      0.655      0.513      -1.281       2.559
horsepower      -0.0236      0.633     -0.037      0.970      -1.269       1.221
weight          -5.3249      0.766     -6.956      0.000      -6.831      -3.819
acceleration     0.4363      0.326      1.337      0.182      -0.206       1.079
model_year       2.6870      0.219     12.246      0.000       2.255       3.119
==============================================================================
Omnibus:                       31.417   Durbin-Watson:                   1.685
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.922
Skew:                           0.646   Prob(JB):                     3.93e-11
Kurtosis:                       4.415   Cond. No.                         12.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
### 평가
from sklearn.metrics import mean_absolute_error

pred = model.predict(test_input)

mae = mean_absolute_error(test_target, pred)
mae

2.5329911176636846

## 문제 2

다음과 같은 OLS 모델을 만들고 결과를 확인합니다.
- mpg 데이터를 사용하여, 상수항을 포함한 OLS 모델을 생성합니다.
- train, test 데이터는 300, 92개를 각각 사용합니다.
- 독립변수는 ["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"]를 사용합니다.
- "origin"은 더미변수를 만들어 사용합니다.
- 종속변수는 "mpg"를 사용합니다.

In [19]:
url = "https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/mpg.csv"

df = pd.read_csv(url)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
1,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
2,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
3,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
4,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
...,...,...,...,...,...,...,...,...,...
387,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
388,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
389,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
390,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
391,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited

In [20]:
## 수동방식

In [24]:
X = df[["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"]]
y = df["mpg"]
X = pd.get_dummies(X, columns=["origin"], drop_first=True, dtype="int")
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,8,318.0,150.0,4096,13.0,71,0,1
1,6,258.0,110.0,2962,13.5,71,0,1
2,6,173.0,115.0,2595,11.3,79,0,1
3,4,140.0,90.0,2408,19.5,72,0,1
4,4,105.0,75.0,2230,14.5,78,0,1
...,...,...,...,...,...,...,...,...
387,4,140.0,72.0,2565,13.6,76,0,1
388,4,72.0,69.0,1613,18.0,71,1,0
389,4,121.0,80.0,2670,15.0,79,0,1
390,8,350.0,145.0,4055,12.0,76,0,1
391,4,151.0,90.0,2670,16.0,79,0,1

In [25]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X[["cylinders", "displacement", "horsepower", 
   "weight", "acceleration", "model_year"]]= ss.fit_transform(X[["cylinders", "displacement", "horsepower",
                                                                 "weight", "acceleration", "model_year"]])
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,1.483947,1.182542,1.184397,1.318391,-0.922327,-1.353505,0,1
1,0.309967,0.608437,0.143869,-0.018371,-0.740861,-1.353505,0,1
2,0.309967,-0.204879,0.273935,-0.450991,-1.539310,0.820978,0,1
3,-0.864014,-0.520637,-0.376395,-0.671427,1.436726,-1.081695,0,1
4,-0.864014,-0.855532,-0.766593,-0.881254,-0.377930,0.549168,0,1
...,...,...,...,...,...,...,...,...
387,-0.864014,-0.520637,-0.844632,-0.486355,-0.704568,0.005547,0,1
388,-0.864014,-1.171290,-0.922672,-1.608575,0.892329,-1.353505,1,0
389,-0.864014,-0.702437,-0.636527,-0.362581,-0.196464,0.820978,0,1
390,1.483947,1.488732,1.054331,1.270061,-1.285258,0.005547,0,1
391,-0.864014,-0.415384,-0.376395,-0.362581,0.166467,0.820978,0,1

In [26]:
X = add_constant(X)
X

,const,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,1.0,1.483947,1.182542,1.184397,1.318391,-0.922327,-1.353505,0,1
1,1.0,0.309967,0.608437,0.143869,-0.018371,-0.740861,-1.353505,0,1
2,1.0,0.309967,-0.204879,0.273935,-0.450991,-1.539310,0.820978,0,1
3,1.0,-0.864014,-0.520637,-0.376395,-0.671427,1.436726,-1.081695,0,1
4,1.0,-0.864014,-0.855532,-0.766593,-0.881254,-0.377930,0.549168,0,1
...,...,...,...,...,...,...,...,...,...
387,1.0,-0.864014,-0.520637,-0.844632,-0.486355,-0.704568,0.005547,0,1
388,1.0,-0.864014,-1.171290,-0.922672,-1.608575,0.892329,-1.353505,1,0
389,1.0,-0.864014,-0.702437,-0.636527,-0.362581,-0.196464,0.820978,0,1
390,1.0,1.483947,1.488732,1.054331,1.270061,-1.285258,0.005547,0,1
391,1.0,-0.864014,-0.415384,-0.376395,-0.362581,0.166467,0.820978,0,1

In [30]:
train_input = X.iloc[:300, :]
test_input = X.iloc[300:, :]
train_input

,const,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,1.0,1.483947,1.182542,1.184397,1.318391,-0.922327,-1.353505,0,1
1,1.0,0.309967,0.608437,0.143869,-0.018371,-0.740861,-1.353505,0,1
2,1.0,0.309967,-0.204879,0.273935,-0.450991,-1.539310,0.820978,0,1
3,1.0,-0.864014,-0.520637,-0.376395,-0.671427,1.436726,-1.081695,0,1
4,1.0,-0.864014,-0.855532,-0.766593,-0.881254,-0.377930,0.549168,0,1
...,...,...,...,...,...,...,...,...,...
295,1.0,-0.864014,-1.133016,-1.364896,-1.566139,0.347933,-0.538074,1,0
296,1.0,1.483947,1.488732,1.574594,0.843334,-1.466724,-1.625315,0,1
297,1.0,1.483947,1.488732,1.054331,1.301888,-0.922327,-0.809884,0,1
298,1.0,0.309967,0.350090,0.013803,0.657083,1.327847,0.549168,0,1
299,1.0,-0.864014,-0.702437,0.195895,-0.129178,-0.014999,-0.809884,0,0

In [31]:
train_target = y.iloc[:300]
test_target = y.iloc[300:]

In [33]:
### 다중선형회귀 모델 적합

model = OLS(train_target, train_input).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     168.0
Date:                Thu, 21 Aug 2025   Prob (F-statistic):          2.55e-104
Time:                        13:10:11   Log-Likelihood:                -782.19
No. Observations:                 300   AIC:                             1582.
Df Residuals:                     291   BIC:                             1616.
Df Model:                           8
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           25.2591      0.519     48.637      0.000      24.237      26.281
cylinders       -0.6685      0.610     -1.096      0.274      -1.870       0.533
displacement     2.1967      0.881      2.492      0.013       0.462       3.931
horsepower      -0.4730      0.589     -0.803      0.422      -1.632       0.686
weight          -5.5164      0.627     -8.802      0.000      -6.750      -4.283
acceleration     0.2592      0.305      0.848      0.397      -0.342       0.860
model_year       2.9173      0.222     13.139      0.000       2.480       3.354
origin_japan     0.0443      0.659      0.067      0.946      -1.252       1.341
origin_usa      -3.0394      0.651     -4.666      0.000      -4.322      -1.757
==============================================================================
Omnibus:                       24.658   Durbin-Watson:                   2.228
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.197
Skew:                           0.516   Prob(JB):                     1.87e-09
Kurtosis:                       4.466   Cond. No.                         11.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [36]:
### 평가
from sklearn.metrics import r2_score

pred = model.predict(test_input)
r2 = r2_score(test_target, pred)

r2

0.8224083082661965

## 문제 3

다음과 같은 OLS 모델을 만들고 결과를 확인합니다.
- mpg 데이터를 사용하여, 상수항을 포함한 OLS 모델을 생성합니다.
- train, test 데이터는 300, 92개를 각각 사용합니다.
- 독립변수는 ["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year"]를 사용합니다.
- 종속변수는 "mpg"를 사용합니다.

In [39]:
url = "https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/mpg.csv"

df = pd.read_csv(url)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
1,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
2,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
3,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
4,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
...,...,...,...,...,...,...,...,...,...
387,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
388,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
389,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
390,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
391,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited

In [44]:
ss = StandardScaler()
df[["cylinders", "displacement", "horsepower", 
    "weight", "acceleration", "model_year"]]= ss.fit_transform(df[["cylinders", "displacement", "horsepower",
                                                                   "weight", "acceleration", "model_year"]])
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,1.483947,1.182542,1.184397,1.318391,-0.922327,-1.353505,usa,plymouth fury iii
1,18.0,0.309967,0.608437,0.143869,-0.018371,-0.740861,-1.353505,usa,amc hornet sportabout (sw)
2,28.8,0.309967,-0.204879,0.273935,-0.450991,-1.539310,0.820978,usa,chevrolet citation
3,20.0,-0.864014,-0.520637,-0.376395,-0.671427,1.436726,-1.081695,usa,chevrolet vega
4,30.9,-0.864014,-0.855532,-0.766593,-0.881254,-0.377930,0.549168,usa,dodge omni
...,...,...,...,...,...,...,...,...,...
387,26.5,-0.864014,-0.520637,-0.844632,-0.486355,-0.704568,0.005547,usa,ford pinto
388,35.0,-0.864014,-1.171290,-0.922672,-1.608575,0.892329,-1.353505,japan,datsun 1200
389,27.4,-0.864014,-0.702437,-0.636527,-0.362581,-0.196464,0.820978,usa,amc spirit dl
390,13.0,1.483947,1.488732,1.054331,1.270061,-1.285258,0.005547,usa,chevy c10
391,28.4,-0.864014,-0.415384,-0.376395,-0.362581,0.166467,0.820978,usa,buick skylark limited

In [45]:
train = df.iloc[:300,:]
test = df.iloc[300:,:]

In [46]:
### formula 방식으로 풀기
from statsmodels.api import OLS

formula = "mpg ~ cylinders + displacement + horsepower + weight + acceleration + model_year"

model = OLS.from_formula(formula, data=train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.804
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     200.3
Date:                Thu, 21 Aug 2025   Prob (F-statistic):          1.46e-100
Time:                        13:21:35   Log-Likelihood:                -796.65
No. Observations:                 300   AIC:                             1607.
Df Residuals:                     293   BIC:                             1633.
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       23.3799      0.202    116.010      0.000      22.983      23.777
cylinders       -0.4349      0.635     -0.685      0.494      -1.684       0.815
displacement     0.3921      0.854      0.459      0.646      -1.288       2.072
horsepower       0.2510      0.598      0.420      0.675      -0.925       1.427
weight          -5.6118      0.649     -8.651      0.000      -6.888      -4.335
acceleration     0.2587      0.319      0.811      0.418      -0.369       0.887
model_year       2.8229      0.227     12.414      0.000       2.375       3.270
==============================================================================
Omnibus:                       40.315   Durbin-Watson:                   2.236
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               71.569
Skew:                           0.758   Prob(JB):                     2.88e-16
Kurtosis:                       4.850   Cond. No.                         10.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [52]:
### 예측 및 평가
from sklearn.metrics import r2_score

pred = model.predict(test)
r2 = r2_score(test["mpg"], pred)
mae = mean_absolute_error(test["mpg"], pred)

print(f"R2-Score : {r2}")
print(f"MAE : {mae}")

R2-Score : 0.818887709591695
MAE : 2.6073197727000994

## 문제 4

다음과 같은 OLS 모델을 만들고 결과를 확인합니다.
- mpg 데이터를 사용하여, 상수항을 포함한 OLS 모델을 생성합니다.
- train, test 데이터는 300, 92개를 각각 사용합니다.
- 독립변수는 ["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"]를 사용합니다.
- "origin"은 더미변수를 만들어 사용합니다.
- 종속변수는 "mpg"를 사용합니다.

In [2]:
url = "https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/mpg.csv"

df = pd.read_csv(url)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
1,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
2,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
3,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
4,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
...,...,...,...,...,...,...,...,...,...
387,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
388,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
389,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
390,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
391,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited

In [3]:
df["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [57]:
### 데이터 분할
train = df.iloc[:300, :]
test = df.iloc[300:, :]

In [ ]:
### 기준나라를 정하고 그 기준 나라에서 해당 나라로 변할때 차이가 유의한지

In [58]:
### formula 방식으로 모델 적합
from statsmodels.api import OLS

formula = "mpg ~ cylinders + displacement + horsepower + weight + acceleration + model_year + C(origin)"

model = OLS.from_formula(formula, data=train).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     168.0
Date:                Thu, 21 Aug 2025   Prob (F-statistic):          2.55e-104
Time:                        13:29:10   Log-Likelihood:                -782.19
No. Observations:                 300   AIC:                             1582.
Df Residuals:                     291   BIC:                             1616.
Df Model:                           8
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            -17.7418      5.332     -3.328      0.001     -28.235      -7.248
C(origin)[T.japan]     0.0443      0.659      0.067      0.946      -1.252       1.341
C(origin)[T.usa]      -3.0394      0.651     -4.666      0.000      -4.322      -1.757
cylinders             -0.3924      0.358     -1.096      0.274      -1.097       0.313
displacement           0.0210      0.008      2.492      0.013       0.004       0.038
horsepower            -0.0123      0.015     -0.803      0.422      -0.042       0.018
weight                -0.0065      0.001     -8.802      0.000      -0.008      -0.005
acceleration           0.0941      0.111      0.848      0.397      -0.124       0.312
model_year             0.7929      0.060     13.139      0.000       0.674       0.912
==============================================================================
Omnibus:                       24.658   Durbin-Watson:                   2.228
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.197
Skew:                           0.516   Prob(JB):                     1.87e-09
Kurtosis:                       4.466   Cond. No.                     8.71e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.71e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [61]:
### 예측 및 평가
from sklearn.metrics import r2_score

pred = model.predict(test)

r2 = r2_score(test["mpg"], pred)
r2

0.8224083082661905

In [63]:
print("""
모형의 설명력을 나타내는 지표 : r2_score
""")

모형의 설명력을 나타내는 지표 : r2_score

In [67]:
### 회귀계수 구하기
model.params

Intercept            -17.741768
C(origin)[T.japan]     0.044325
C(origin)[T.usa]      -3.039433
cylinders             -0.392424
displacement           0.021019
horsepower            -0.012304
weight                -0.006503
acceleration           0.094065
model_year             0.792945
dtype: float64

In [72]:
### p-value 구하기
model.pvalues[1:].round(3)

C(origin)[T.japan]    0.946
C(origin)[T.usa]      0.000
cylinders             0.274
displacement          0.013
horsepower            0.422
weight                0.000
acceleration          0.397
model_year            0.000
dtype: float64

In [73]:
### t 통계량 구하기
model.tvalues

Intercept             -3.327558
C(origin)[T.japan]     0.067285
C(origin)[T.usa]      -4.665826
cylinders             -1.095530
displacement           2.492460
horsepower            -0.803479
weight                -8.801962
acceleration           0.848455
model_year            13.138552
dtype: float64

In [74]:
### f통계량 구하기
model.fvalue

167.9938169027532

In [75]:
### f통계량의 p-value
model.f_pvalue

2.548448663292696e-104